version: "3"

services:
  gazebo:
    image: test
    user: user
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY="/tmp/.docker.xauth"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /tmp/.gazebo/:/root/.gazebo/:rw
    devices:
      - /dev/dri:/dev/dri
    command: gazebo 
